LogisticRegression: LogisticRegression,
KNeighborsClassifier: KNeighborsClassifier,
SVC": SVC,
NaiveBayes: GaussianNB,
DecisionTreeClassifier: DecisionTreeClassifier,
RandomForestClassifier: RandomForestClassifier,
XGBClassifier: XGBClassifier,
LGBMClassifier: LGBMClassifier,