scalers:
  NoScaling: null

  StandardScaler:
    module: sklearn.preprocessing
    class: StandardScaler
    params: { }
  MinMaxScaler:
    module: sklearn.preprocessing
    class: MinMaxScaler
    params: { }